# Generated by Django 2.2.6 on 2019-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20191105_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombreCientificoEspecie',
            field=models.CharField(max_length=30, verbose_name='Nombre Cientifico'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombreComunEspecie',
            field=models.CharField(max_length=30, verbose_name='Nombre Común'),
        ),
    ]
