# Generated by Django 2.2.6 on 2019-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20191106_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='fotoGenero',
            field=models.ImageField(default='', upload_to='static/imagenes'),
        ),
    ]
