# Generated by Django 2.2.6 on 2019-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20191111_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='ubicacion',
            field=models.CharField(choices=[('Campus Río Vena', 'Campus Río Vena'), ('Hospital del Rey', 'Hospital del Rey'), ('Hospital Militar', 'Hospital Militar'), ('Campus Facultad de Educación', 'Campus Facultad de Educación'), ('Campus Facultad de Ciencias', 'Campus Facultad de Ciencias')], max_length=50, verbose_name='Ubicación'),
        ),
    ]
