# Generated by Django 2.2.6 on 2019-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20191111_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='nombreComun',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nombre Común'),
        ),
    ]
