# Generated by Django 2.2.6 on 2019-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_auto_20191111_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='y',
            field=models.DecimalField(decimal_places=19, default=1, max_digits=19, verbose_name='Y'),
        ),
    ]
