# Generated by Django 2.2.6 on 2019-11-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_auto_20191111_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individuos',
            options={'ordering': ['especie']},
        ),
    ]
