# Generated by Django 2.2 on 2019-05-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=30, unique=True, verbose_name='Nombre Cientifico')),
                ('nombreComun', models.CharField(max_length=30, unique=True, verbose_name='Nombre Común')),
                ('autoctona', models.BooleanField(default=False, verbose_name='Autóctona')),
                ('distribucion', models.TextField(verbose_name='Distribucion')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('ecologia', models.TextField(verbose_name='Ecologia')),
                ('masInfo', models.TextField(verbose_name='Más Información')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Familia')),
            ],
        ),
    ]
