# Generated by Django 2.2 on 2019-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('ecologia', models.CharField(blank=True, max_length=200, verbose_name='Ecologia')),
                ('distribucion', models.CharField(blank=True, max_length=200, verbose_name='Distribucion')),
            ],
        ),
    ]
