# Generated by Django 2.2 on 2019-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('motivoSingular', models.TextField(verbose_name='Motivo de Singularidad')),
                ('x', models.IntegerField(default=1, verbose_name='X')),
                ('y', models.IntegerField(default=1, verbose_name='Y')),
                ('fotoArbol', models.ImageField(upload_to='photos')),
                ('fotoHojas', models.ImageField(blank=True, upload_to='photos')),
                ('fotoTronco', models.ImageField(blank=True, upload_to='photos')),
                ('fotoFrutos', models.ImageField(blank=True, upload_to='photos')),
                ('altura', models.IntegerField(default=1, verbose_name='Altura')),
                ('perimetro', models.IntegerField(default=1, verbose_name='Perimetro')),
            ],
        ),
    ]
