# Generated by Django 2.2 on 2019-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0002_individuos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='fotoArbol',
            field=models.ImageField(upload_to='templates/pantallaPrincipal'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoFrutos',
            field=models.ImageField(blank=True, upload_to='templates/pantallaPrincipal'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoHojas',
            field=models.ImageField(blank=True, upload_to='templates/pantallaPrincipal'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoTronco',
            field=models.ImageField(blank=True, upload_to='templates/pantallaPrincipal'),
        ),
    ]
