# Generated by Django 2.2 on 2019-04-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0002_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='distribucion',
            field=models.TextField(blank=True, verbose_name='Distribucion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='ecologia',
            field=models.TextField(blank=True, verbose_name='Ecologia'),
        ),
        migrations.CreateModel(
            name='Individuos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIndividuos', models.CharField(max_length=80, verbose_name='nombre_Individuos')),
                ('caracteristicas', models.TextField(blank=True, verbose_name='Caracteristicas')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie')),
            ],
        ),
    ]
