# Generated by Django 2.2 on 2019-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0003_auto_20190502_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='fotoArbol',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoFrutos',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoHojas',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='fotoTronco',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
