# Generated by Django 2.2 on 2019-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0004_auto_20190508_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='distribucion',
            field=models.TextField(choices=[('AS', 'Asia'), ('AN', 'Antártida'), ('EU', 'Europa'), ('AF', 'África'), ('OC', 'Oceanía'), ('AM', 'América')], verbose_name='Distribucion'),
        ),
    ]
