# Generated by Django 2.2 on 2019-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0006_auto_20190425_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombreEspecie',
            field=models.CharField(max_length=80, unique=True, verbose_name='nombre_Especie'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='nombreIndividuos',
            field=models.CharField(max_length=80, unique=True, verbose_name='nombre_Individuos'),
        ),
    ]
