# Generated by Django 2.2 on 2019-05-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0008_auto_20190509_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuos',
            name='especie',
        ),
    ]
