# Generated by Django 2.2 on 2019-05-09 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0009_remove_individuos_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuos',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie'),
        ),
    ]
