# Generated by Django 2.2 on 2019-05-09 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0010_individuos_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie'),
        ),
    ]
