# Generated by Django 2.2 on 2019-05-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0013_auto_20190509_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuos',
            name='tipoEspecie',
        ),
        migrations.AddField(
            model_name='individuos',
            name='tipo_especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie'),
        ),
    ]
