# Generated by Django 2.2 on 2019-05-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0014_auto_20190509_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individuos',
            old_name='tipo_especie',
            new_name='tipoEspecie',
        ),
    ]
