# Generated by Django 2.2 on 2019-05-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0015_auto_20190509_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuos',
            name='tipoEspecie',
        ),
    ]
