# Generated by Django 2.2 on 2019-05-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0016_remove_individuos_tipoespecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuos',
            name='tipoEspecie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie'),
        ),
    ]
