# Generated by Django 2.2 on 2019-05-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0017_individuos_tipoespecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='tipoEspecie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especie'),
        ),
    ]
