# Generated by Django 2.2 on 2019-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0018_auto_20190510_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(default='', max_length=30, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primerApellido',
            field=models.CharField(default='', max_length=30, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(default='', max_length=30, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
