# Generated by Django 2.2 on 2019-05-13 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0019_auto_20190510_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Familia', unique=True),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='motivoSingular',
            field=models.CharField(choices=[('AN', 'Antigüedad'), ('DI', 'Elevado Diámetro'), ('HI', 'Lo plantó un personaje histórico')], max_length=30, verbose_name='Motivo de Singularidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
    ]
