# Generated by Django 2.2 on 2019-05-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0020_auto_20190513_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Familia'),
        ),
    ]
