# Generated by Django 2.2 on 2019-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0021_auto_20190513_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=30, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primerApellido',
            field=models.CharField(max_length=30, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(max_length=30, verbose_name='Segundo Apellido'),
        ),
    ]
