# Generated by Django 2.2 on 2019-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0024_auto_20190513_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especie',
            old_name='nombreCientifico',
            new_name='nombreCientificoEspecie',
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='nombreComun',
            new_name='nombreComunEspecie',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='nombre',
            new_name='nombreFamilia',
        ),
        migrations.RenameField(
            model_name='individuos',
            old_name='tipoEspecie',
            new_name='nombreComun',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombreUsuario',
        ),
        migrations.RemoveField(
            model_name='individuos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='individuos',
            name='explicacionMotivoSingular',
            field=models.CharField(default='', max_length=30, verbose_name='Explicacion'),
        ),
    ]
