# Generated by Django 2.2 on 2019-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0025_auto_20190521_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='distribucion',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='masInfo',
        ),
        migrations.AlterField(
            model_name='individuos',
            name='motivoSingular',
            field=models.CharField(choices=[('Antigüedad', 'Antigüedad'), ('Elevado Diámetro', 'Elevado Diámetro'), ('Plantado por un personaje histórico', 'Plantado por un personaje histórico'), ('Vistosidad', 'Vistosidad'), ('Madera codiciada', 'Madera codiciada'), ('Frutos peculiares', 'Frutos peculiares'), ('Utilidad medicinal', 'Utilidad medicinal')], max_length=30, verbose_name='Motivo de Singularidad'),
        ),
    ]
