# Generated by Django 2.2 on 2019-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0026_auto_20190522_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='explicacionMotivoSingular',
            field=models.TextField(verbose_name='Explicacion'),
        ),
    ]
