# Generated by Django 2.2 on 2019-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0028_auto_20190522_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='motivoSingular',
            field=models.CharField(choices=[('Antigüedad', 'Antigüedad'), ('Elevado Diámetro', 'Elevado Diámetro'), ('Plantado por un personaje histórico', 'Plantado por un personaje histórico'), ('Vistosidad', 'Vistosidad'), ('Madera codiciada', 'Madera codiciada'), ('Frutos peculiares', 'Frutos peculiares'), ('Utilidad medicinal', 'Utilidad medicinal')], max_length=50, verbose_name='Motivo de Singularidad'),
        ),
    ]
