# Generated by Django 2.2 on 2019-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0029_auto_20190522_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='id',
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombreComunEspecie',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Nombre Común'),
        ),
    ]
