# Generated by Django 2.2 on 2019-05-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0030_auto_20190522_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individuos',
            name='id',
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombreComunEspecie',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Común'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombreFamilia',
            field=models.CharField(choices=[('Aceráceas', 'Aceráceas'), ('Anacardiáceas', 'Anacardiáceas'), ('Aquifoliáceas', 'Aquifoliáceas'), ('Betuláceas', 'Betuláceas'), ('Buxáceas', 'Buxáceas'), ('Caprifoliáceas', 'Caprifoliáceas'), ('Celastráceas', 'Celastráceas'), ('Cornáceas', 'Cornáceas'), ('Cupresáceas', 'Cupresáceas'), ('Eleagnáceas', 'Eleagnáceas'), ('Ericácas', 'Ericácas'), ('Fagáceas', 'Fagáceas'), ('Juglandáceas', 'Juglandáceas'), ('Lauráceas', 'Lauráceas'), ('Leguminosas', 'Leguminosas'), ('Meliáceas', 'Meliáceas'), ('Mirtáceas', 'Mirtáceas'), ('Moráceas', 'Moráceas'), ('Oleáceas', 'Oleáceas'), ('Palmáceas', 'Palmáceas'), ('Pináceas', 'Pináceas'), ('Platanáceas', 'Platanáceas'), ('Punicáceas', 'Punicáceas'), ('Ramnáceas', 'Ramnáceas'), ('Rosáceas', 'Rosáceas'), ('Salicáceas', 'Salicáceas'), ('Simaroubáceas', 'Simaroubáceas'), ('Solanáceas', 'Solanáceas'), ('Tamariacáceas', 'Tamariacáceas'), ('Taxáceas', 'Taxáceas'), ('Tiliáceas', 'Tiliáceas'), ('Ulmáceas', 'Ulmáceas')], max_length=30, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='nombreComun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pantallaPrincipal.Especie'),
        ),
    ]
