# Generated by Django 2.2 on 2019-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0036_auto_20190522_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nombreCientificoEspecie',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nombre Cientifico'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombreComunEspecie',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre Común'),
        ),
    ]
