# Generated by Django 2.2 on 2019-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0037_auto_20190522_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especie',
            new_name='Especies',
        ),
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familias',
        ),
    ]
