# Generated by Django 2.2 on 2019-05-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0038_auto_20190522_1847'),
    ]

    operations = [
        migrations.RenameModel('Especies', 'Especie'),
        migrations.RenameModel('Familias', 'Familia'),
    ]
