# Generated by Django 2.2 on 2019-05-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0039_auto_20190527_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientificoEspecie', models.CharField(max_length=30, unique=True, verbose_name='Nombre Cientifico')),
                ('nombreComunEspecie', models.CharField(max_length=30, unique=True, verbose_name='Nombre Común')),
                ('autoctona', models.BooleanField(default=False, verbose_name='Autóctona')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('ecologia', models.TextField(verbose_name='Ecologia')),
            ],
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFamilia', models.CharField(choices=[('Aceráceas', 'Aceráceas'), ('Anacardiáceas', 'Anacardiáceas'), ('Aquifoliáceas', 'Aquifoliáceas'), ('Betuláceas', 'Betuláceas'), ('Buxáceas', 'Buxáceas'), ('Caprifoliáceas', 'Caprifoliáceas'), ('Celastráceas', 'Celastráceas'), ('Cornáceas', 'Cornáceas'), ('Cupresáceas', 'Cupresáceas'), ('Eleagnáceas', 'Eleagnáceas'), ('Ericácas', 'Ericácas'), ('Fagáceas', 'Fagáceas'), ('Juglandáceas', 'Juglandáceas'), ('Lauráceas', 'Lauráceas'), ('Leguminosas', 'Leguminosas'), ('Meliáceas', 'Meliáceas'), ('Mirtáceas', 'Mirtáceas'), ('Moráceas', 'Moráceas'), ('Oleáceas', 'Oleáceas'), ('Palmáceas', 'Palmáceas'), ('Pináceas', 'Pináceas'), ('Platanáceas', 'Platanáceas'), ('Punicáceas', 'Punicáceas'), ('Ramnáceas', 'Ramnáceas'), ('Rosáceas', 'Rosáceas'), ('Salicáceas', 'Salicáceas'), ('Simaroubáceas', 'Simaroubáceas'), ('Solanáceas', 'Solanáceas'), ('Tamariacáceas', 'Tamariacáceas'), ('Taxáceas', 'Taxáceas'), ('Tiliáceas', 'Tiliáceas'), ('Ulmáceas', 'Ulmáceas')], max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='individuos',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='altura',
            field=models.IntegerField(default=0, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='nombreComun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Especies'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='perimetro',
            field=models.IntegerField(default=0, verbose_name='Perimetro'),
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.AddField(
            model_name='especies',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantallaPrincipal.Familias'),
        ),
    ]
