# Generated by Django 2.2 on 2019-05-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0040_auto_20190527_1404'),
    ]

    operations = [
    ]
