# Generated by Django 2.2.1 on 2019-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0003_auto_20190529_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='idEspecie',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='idFamilia',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='idIndividuo',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
