# Generated by Django 2.2.1 on 2019-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantallaPrincipal', '0005_auto_20190529_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuos',
            name='x',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='individuos',
            name='y',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19, verbose_name='Y'),
        ),
    ]
